MVC_Assignement1/Models/FevercheckModel.cs
using System;
namespace MVC_Assignement1.Models
{
	public class FevercheckModel
	{
       public static string Fever_check(double temp, string scale)
       {
           string ret = "";
            if (scale == "Celsius")
             {
                if (temp > 37) ret = "You have fever";
                else if (temp < 35) ret = "you have hypothermis";
                else ret = "your temparature is normal";
             }
             if (scale == "Fahrenheit")
             {
                 if (temp > 100.4) ret = "You have fever";
                 else if (temp < 95) ret = "you have hypothermis";
                 else ret = "Your temparature is normal";
             }
                return ret;
       }

        
	}
}

MVC_Assignement1/Models/GameModel.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;
namespace MVC_Assignement1.Models
{
	public class GameModel
	{
		public static List<int> store_num = new List<int>();

		public static int GetGuessNumber()
		{
			var random = new Random();
			int num = random.Next(1, 100);
			store_num.Clear();
			return num;
		}
		public static string CheckGuess(int Submit, int guess)
        {
			if (Submit <= 100 && Submit >= 1)
			{
				store_num.Add(Submit);
				if (Submit > guess)
				{
					return "your guess is too high";
				}
				else if (Submit < guess)
				{
					return "your guess is too low";
				}
				else
				{
					return "Congratulations";
				}
			}
            else
            {
				return "please enter a valid number";
            }
			
        }
	}
}

MVC_Assignement1/Controllers/DoctorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MVC_Assignement1.Models;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MVC_Assignement1.Controllers
{
    public class DoctorController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index(double input_temp, string Temperature)
        {
            ViewBag.temperature = input_temp;
            ViewBag.result = FevercheckModel.Fever_check(input_temp, Temperature);
            return View();

        }
    }
}

MVC_Assignement1/Controllers/GuessgameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC_Assignement1.Models;
using Microsoft.AspNetCore.Http;
using System.Diagnostics;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MVC_Assignement1.Controllers
{
    public class GuessgameController : Controller
    {
        [HttpGet] 
        public IActionResult GuessView()
        {
            int rand_num = GameModel.GetGuessNumber();
            HttpContext.Session.SetInt32("rndvalue", rand_num);
            return View();
        }
        [HttpPost]
        public IActionResult Guessview(int input_num)
        {
            int game_num = (int)HttpContext.Session.GetInt32("rndvalue");
            ViewBag.Message = GameModel.CheckGuess(input_num, game_num);
            return View("GuessView");

        }

        public IActionResult Reset()
        {
            GameModel.store_num.Clear();
            int rand_num = GameModel.GetGuessNumber();
            HttpContext.Session.SetInt32("randval", rand_num);
            return View("GuessView");
        }
        
    }
}

MVC_Assignement1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MVC_Assignement1.Controllers
{
    public class HomeController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult About()
        {
            return View();
        }
        public IActionResult Contact()
        {
            return View();
        }
        public IActionResult Projects()
        {
            return View();
        }
    }
}

MVC_Assignement1/Views/Doctor/Index.cshtml
@model IEnumerable<MVC_Assignement1.Models.FevercheckModel>

@{


    ViewBag.Title = "Fever_Check";
}

<h2>CheckFever</h2>

<form action="/Doctor/Index/" method="post">
    <div>

        Enter Temp:<input type="number" name="input_temp" id="msg" step="any"><br />
        <input type="radio" id="tempChoice1"
               name="Temperature" value="Celsius" checked>
        <label for="tempChoice1">Celsius</label><br />
        <input type="radio" id="tempChoice2"
               name="Temperature" value="Fahrenheit">
        <label for="tempChoice2">Fahrenheit</label><br />
    </div>
    <div>
        <input type="submit" value="Submit">
    </div>
    @{
        var data = ViewBag.temperature;
    }

<h2>
    @if (data != 0)
        {
            @ViewBag.result
        }
</h2>
</form>

MVC_Assignement1/Views/Guessgame/GuessView.cshtml
@{
    ViewBag.Title = "GuessView";
}
<h2> Gussing Game</h2>
<h3> Guess a number in between 1 to 100.</h3>
<form id="tempForm" name="tempForm" action="/Guessgame/GuessView" method="post">
    <label>Enter a number</label>
    <input id="input_num" name="input_num" type="number" min="1" placeholder="Enter number" required autofocus />
    <input type="submit" name="submit_value" value="Submit" />
</form>


<h2 class="text-success">@ViewBag.Message</h2>
@if (ViewBag.Message == "Congratulations")
{
    <p>your guess count is:@MVC_Assignement1.Models.GameModel.store_num.Count</p>
    <p>your inputs are:</p>
}
@for (int i = 0; i < @MVC_Assignement1.Models.GameModel.store_num.Count; i++)
{
    <p>@MVC_Assignement1.Models.GameModel.store_num[i]</p>
}

<form id="tempForm" name="tempForm" action="/Guessgame/Reset" method="post">
    <input type="submit" name="Reset" value="Reset"/>
    <br />
    <br />
</form>

MVC_Assignement1/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h1>@ViewData["Title"]</h1>

<div class="Cotainer">
    <p class="text-justify">
        My name is Priyanka Jayanthi.I came to Sweden in 2017.I did my SASG and currently doing Lexicon DotNet programming.I am a jobseeker for
        fortend developer.
        </p>
</div>
<div class="container">
    <h2>Skills</h2>
    <ul>
        <li>
            <b>Programming Languages:</b>C, HTML, CSS,Java(basic).
        </li>
        <li>
            PowerBI tools
        </li>
        <li>
            Dyalog APL
        </li>
    </ul>
     
</div>

MVC_Assignement1/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h1>Contact Information</h1>
<b>Contact Number:</b> 072144563
<br />
<b> E-Mail Id:</b>jp7483@gmail.com.
<br />
<b>Address</b>
<b>Country:</b>Sweden.
<br />
<b>City:</b>Göthenborg.
<br />
<b>Street:</b>Backable.
<br /><br />

MVC_Assignement1/Views/Home/Index.cshtml
@{
   <h1>Welcome</h1>
    }

MVC_Assignement1/Views/Home/Projects.cshtml
@{
    ViewData["Title"] = "Projects";
}
<h1>My github projects</h1>
<nav>
    <ul>
    <li>
        Calculator program to perfom basic mathematical operations like Addition,Subtraction,Division,Multplication.
        <a href="https://github.com/PriyankaJayanthi/Calculator_Assignment">Calculator Assignement</a>
    </li>
    <li>
        Hangman program is the gussing word game.
        <a href="https://github.com/PriyankaJayanthi/Hangman_Assignment">Hangman Assinement</a>

    </li>
        <li>
            Calculator using xUnit means self testing the program by giving values.
            <a href="https://github.com/PriyankaJayanthi/Calculator_xUint_Assignement">xUnit Assignement</a>
        </li>
        <li>
            Sokobanbase game by using javascript.Sokoban means there is a map with walls,blocks,goles and player.Player must move all the blocks to the goal point.
            <a href="https://github.com/PriyankaJayanthi/JavaScript">Javascript Assignement</a>
        </li>
    </ul>
</nav>
    

MVC_Assignement1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/bootstrap/css/bootstrap.css" />
    
</head>
<body>
    <header>
        <img src="~/img/homeimg.jpeg" />
       <nav>
           <div>
               <ul>
                   <li>
                       <a class="nav_link"> @Html.ActionLink("Home", "Index", "Home", null, new { @class = "actionLink" }) </a>
                   </li>
                   <li>
                       <a class="nav_link"> @Html.ActionLink("About", "About", "Home", null, new { @class = "actionLink" }) </a>
                   </li>
                   <li>
                       <a class="nav_link"> @Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "actionLink" }) </a>
                   </li>
                   <li>
                       <a class="nav_link"> @Html.ActionLink("Projects", "Projects", "Home", null, new { @class = "actionLink" }) </a>
                   </li>
                   <li>
                       <a class="nav_link"> @Html.ActionLink("Doctor", "Index", "Doctor", null, new { @class = "actionLink" }) </a>
                   </li>
                   <li>
                       <a class="nav_link"> @Html.ActionLink("Gussegame", "GuessView", "Guessgame", null, new { @class = "actionLink" }) </a>
                   </li>
               </ul>
           </div>
       </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer>©Jayanthi Priyanka @DateTime.Now.ToString("yy-MM-dd")</footer>

</body>
</html>

MVC_Assignement1/Views/_ViewPort.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers